/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.TreeAndIndexGeneratorCodePlug+<GeneratorIServiceCodeAsync>d__7.MoveNext */
using Materal.MergeBlock.Abstractions.Models;
using MMB.Demo.Abstractions.DTO.MyCategory;

namespace MMB.Demo.Abstractions.Services;

/// <summary>
/// 服务(TreeAndIndex)
/// </summary>
public partial interface IMyCategoryService
{
    /// <summary>
    /// 获得树列表
    /// </summary>
    /// <param name="parentID"></param>
    /// <returns></returns>
    Task<List<MyCategoryTreeListDTO>> GetTreeListAsync(Guid? parentID);

    /// <summary>
    /// 移动树节点
    /// </summary>
    /// <param name="model"></param>
    /// <returns></returns>
    Task MoveTreeNodeAsync(MoveTreeNodeAndIndexModel model);
}