/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesGeneratorCodePlug.GeneratorIServicesCodeAsync */

using MMB.Demo.Abstractions.DTO.MyCategory;
using MMB.Demo.Abstractions.Services.Models.MyCategory;

namespace MMB.Demo.Abstractions.Services
{
    /// <summary>
    /// 服务
    /// </summary>
    public partial interface IMyCategoryService : IBaseService<AddMyCategoryModel, EditMyCategoryModel, QueryMyCategoryModel, MyCategoryDTO, MyCategoryListDTO>
    {
    }
}
