/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesGeneratorCodePlug.GeneratorIServicesCodeAsync */

using MMB.Demo.Abstractions.DTO.MyList;
using MMB.Demo.Abstractions.Services.Models.MyList;

namespace MMB.Demo.Abstractions.Services
{
    /// <summary>
    /// 服务
    /// </summary>
    public partial interface IMyListService : IBaseService<AddMyListModel, EditMyListModel, QueryMyListModel, MyListDTO, MyListListDTO>
    {
    }
}
