/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.IndexGeneratorCodePlug+<GeneratorIServiceCodeAsync>d__11.MoveNext */
using Materal.MergeBlock.Abstractions.Models;

namespace MMB.Demo.Abstractions.Services;

/// <summary>
/// 服务(Index)
/// </summary>
public partial interface IMyListService
{
    /// <summary>
    /// 移动位序
    /// </summary>
    /// <param name="model"></param>
    /// <returns></returns>
    Task MoveIndexAsync(MoveIndexModel model);
}