/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.TreeGeneratorCodePlug+<GeneratorIServiceCodeAsync>d__12.MoveNext */
using Materal.MergeBlock.Abstractions.Models;
using MMB.Demo.Abstractions.DTO.MyTree;

namespace MMB.Demo.Abstractions.Services;

/// <summary>
/// 服务(Tree)
/// </summary>
public partial interface IMyTreeService
{
    /// <summary>
    /// 获得树列表
    /// </summary>
    /// <param name="parentID"></param>
    /// <returns></returns>
    Task<List<MyTreeTreeListDTO>> GetTreeListAsync(Guid? parentID);

    /// <summary>
    /// 移动树节点
    /// </summary>
    /// <param name="model"></param>
    /// <returns></returns>
    Task MoveTreeNodeAsync(MoveTreeNodeModel model);
}