/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesGeneratorCodePlug.GeneratorIServicesCodeAsync */

using MMB.Demo.Abstractions.DTO.MyTree;
using MMB.Demo.Abstractions.Services.Models.MyTree;

namespace MMB.Demo.Abstractions.Services
{
    /// <summary>
    /// 服务
    /// </summary>
    public partial interface IMyTreeService : IBaseService<AddMyTreeModel, EditMyTreeModel, QueryMyTreeModel, MyTreeDTO, MyTreeListDTO>
    {
    }
}
