/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorRepositoryImplCodeAsync>d__12.MoveNext */

namespace MMB.Demo.Repository.Repositories;
/// <summary>
/// 仓储
/// </summary>

public partial class MyCategoryRepositoryImpl(DemoDBContext dbContext) : DemoRepositoryImpl<MyCategory>(dbContext), IMyCategoryRepository, IScopedDependency<IMyCategoryRepository>
{

}
