/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.IndexGeneratorCodePlug+<GeneratorRepositoryImplCodeAsync>d__9.MoveNext */
namespace MMB.Demo.Repository.Repositories;
/// <summary>
/// 仓储(Index)
/// </summary>
public partial class MyCategoryRepositoryImpl
{
    /// <summary>
    /// 获取最大位序
    /// </summary>
    /// <param name="parentID"></param>
    /// <returns></returns>
    public async Task<int> GetMaxIndexAsync(Guid? parentID)
    {
        if (!await DBSet.AnyAsync(m => m.ParentID == parentID)) return -1;
        int result = await DBSet.Where(m => m.ParentID == parentID).MaxAsync(m => m.Index);
        return result;
    }
}