/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.TreeGeneratorCodePlug+<GeneratorRepositoryImplCodeAsync>d__8.MoveNext */
namespace MMB.Demo.Repository.Repositories;
/// <summary>
/// 仓储(Tree)
/// </summary>
public partial class MyCategoryRepositoryImpl
{
    /// <summary>
    /// 获取指定节点的递归子级
    /// </summary>
    /// <param name="parentID">父节点ID</param>
    /// <returns>所有递归子级</returns>
    public List<MyCategory> GetAllRecursiveChildren(Guid parentID)
    {
        const string sql = """
            WITH TreeNodes(ID, CreateTime, UpdateTime, Name, ParentID, Index, Depth) AS (
                SELECT ID, CreateTime, UpdateTime, Name, ParentID, Index, 0 AS Depth
                FROM MyCategory
                WHERE ID = @RootID
                UNION ALL
                SELECT child.ID, child.CreateTime, child.UpdateTime, child.Name, child.ParentID, child.Index, parent.Depth + 1
                FROM MyCategory child
                INNER JOIN TreeNodes parent ON child.ParentID = parent.ID
            )
            SELECT *
            FROM TreeNodes
            ORDER BY Depth DESC;
            """;
        return ExcuteQuerySql<MyCategory>(sql, [GetParameter("@RootID", parentID)]);
    }

    /// <summary>
    /// 获取指定节点的递归子级唯一标识
    /// </summary>
    /// <param name="parentID">父节点ID</param>
    /// <returns>所有递归子级ID</returns>
    public List<Guid> GetAllRecursiveChildrenID(Guid parentID)
    {
        const string sql = """
            WITH TreeNodes(ID, Depth) AS (
                SELECT ID, 0 AS Depth
                FROM MyCategory
                WHERE ID = @RootID
                UNION ALL
                SELECT child.ID, parent.Depth + 1
                FROM MyCategory child
                INNER JOIN TreeNodes parent ON child.ParentID = parent.ID
            )
            SELECT ID
            FROM TreeNodes
            ORDER BY Depth DESC;
            """;
        return ExcuteQuerySql(sql, [GetParameter("@RootID", parentID)], dr => dr.GetGuid(0));
    }
}