/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.IndexGeneratorCodePlug+<GeneratorRepositoryImplCodeAsync>d__9.MoveNext */
namespace MMB.Demo.Repository.Repositories;
/// <summary>
/// 仓储(Index)
/// </summary>
public partial class MyListRepositoryImpl
{
    /// <summary>
    /// 获取最大位序
    /// </summary>
    /// <returns></returns>
    public async Task<int> GetMaxIndexAsync()
    {
        if (!await DBSet.AnyAsync()) return -1;
        int result = await DBSet.MaxAsync(m => m.Index);
        return result;
    }
}