/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorRepositoryImplCodeAsync>d__12.MoveNext */

namespace MMB.Demo.Repository.Repositories;
/// <summary>
/// 用户仓储
/// </summary>

public partial class UserRepositoryImpl(DemoDBContext dbContext) : DemoRepositoryImpl<User>(dbContext), IUserRepository, IScopedDependency<IUserRepository>
{

}
