/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RequesetModelGeneratorCodePlug+<GeneratorEditRequestModelAsync>d__9.MoveNext */

namespace MMB.Demo.Abstractions.RequestModel.MyCategory;
/// <summary>
/// 修改请求模型
/// </summary>
public partial class EditMyCategoryRequestModel : IEditRequestModel
{
    /// <summary>
    /// 唯一标识
    /// </summary>
    [Required(ErrorMessage = "唯一标识为空")]
    public Guid ID { get; set; }
    [Required]
    public string Name { get; set; } = string.Empty;
}
