/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RequesetModelGeneratorCodePlug+<GeneratorQueryRequestModelAsync>d__10.MoveNext */

namespace MMB.Demo.Abstractions.RequestModel.MyCategory;
/// <summary>
/// 查询请求模型
/// </summary>
public partial class QueryMyCategoryRequestModel : PageRequestModel, IQueryRequestModel
{
    /// <summary>
    /// 唯一标识组
    /// </summary>
    public List<Guid>? IDs { get; set; }
    /// <summary>
    /// 最小创建时间
    /// </summary>
    public DateTime? MinCreateTime { get; set; }
    /// <summary>
    /// 最大创建时间
    /// </summary>
    public DateTime? MaxCreateTime { get; set; }
}
