/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RequesetModelGeneratorCodePlug+<GeneratorAddRequestModelAsync>d__8.MoveNext */

namespace MMB.Demo.Abstractions.RequestModel.User;
/// <summary>
/// 用户添加请求模型
/// </summary>
public partial class AddUserRequestModel : IAddRequestModel
{
    /// <summary>
    /// 姓名
    /// </summary>
    [Required(ErrorMessage = "姓名为空"), StringLength(100, ErrorMessage = "姓名过长")]
    public string Name { get; set; } = string.Empty;
    /// <summary>
    /// 角色
    /// </summary>
    [Required(ErrorMessage = "角色为空")]
    public UserRole Role { get; set; }
    /// <summary>
    /// 账号
    /// </summary>
    [Required(ErrorMessage = "账号为空"), StringLength(50, ErrorMessage = "账号过长")]
    public string Account { get; set; } = string.Empty;
}
