/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesModelGeneratorCodePlug+<GeneratorEditModelAsync>d__9.MoveNext */

namespace MMB.Demo.Abstractions.Services.Models.MyTree;
/// <summary>
/// 修改模型
/// </summary>
public partial class EditMyTreeModel : IEditServiceModel
{
    /// <summary>
    /// 唯一标识
    /// </summary>
    [Required(ErrorMessage = "唯一标识为空")]
    public Guid ID { get; set; }
    [Required]
    public string Name { get; set; } = string.Empty;
}
