/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesModelGeneratorCodePlug+<GeneratorQueryModelAsync>d__10.MoveNext */

namespace MMB.Demo.Abstractions.Services.Models.MyTree;
/// <summary>
/// 查询模型
/// </summary>
public partial class QueryMyTreeModel : PageRequestModel, IQueryServiceModel
{
    /// <summary>
    /// 唯一标识组
    /// </summary>
    [Contains("ID")]
    public List<Guid>? IDs { get; set; }
    /// <summary>
    /// 最小创建时间
    /// </summary>
    [GreaterThanOrEqual("CreateTime")]
    public DateTime? MinCreateTime { get; set; }
    /// <summary>
    /// 最大创建时间
    /// </summary>
    [LessThanOrEqual("CreateTime")]
    public DateTime? MaxCreateTime { get; set; }
}
