<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../../../Common.props" />
	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\MMB.Core\MMB.Core.Repository\MMB.Core.Repository.csproj" />
		<ProjectReference Include="..\MMB.Demo.Abstractions\MMB.Demo.Abstractions.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Update="MMB.Demo.Repository.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>