<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../../../Common.props" />
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\MMB.Core\MMB.Core.Repository\MMB.Core.Repository.csproj" />
		<ProjectReference Include="..\MMB.Demo.Abstractions\MMB.Demo.Abstractions.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Update="MMB.Demo.Repository.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
