/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesGeneratorCodePlug.GeneratorServiceImplsCodeAsync */

using MMB.Demo.Abstractions.DTO.MyCategory;
using MMB.Demo.Abstractions.Services.Models.MyCategory;

namespace MMB.Demo.Application.Services
{
    /// <summary>
    /// 服务
    /// </summary>
    public partial class MyCategoryServiceImpl : BaseServiceImpl<AddMyCategoryModel, EditMyCategoryModel, QueryMyCategoryModel, MyCategoryDTO, MyCategoryListDTO, IMyCategoryRepository, MyCategory, IDemoUnitOfWork>, IMyCategoryService, IScopedDependency<IMyCategoryService>
    {
    }
}
