/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.TreeAndIndexGeneratorCodePlug+<GeneratorServiceImplCodeAsync>d__9.MoveNext */
using Materal.MergeBlock.Abstractions.Models;
using MMB.Demo.Abstractions.Domain;
using MMB.Demo.Abstractions.DTO.MyCategory;
using Materal.Utils.Enums;

namespace MMB.Demo.Application.Services;

/// <summary>
/// 服务(TreeAndIndex)
/// </summary>
public partial class MyCategoryServiceImpl
{
    /// <summary>
    /// 获得树列表
    /// </summary>
    /// <param name="parentID"></param>
    /// <returns></returns>
    public async Task<List<MyCategoryTreeListDTO>> GetTreeListAsync(Guid? parentID)
    {
        Dictionary<string, object> contextData = [];
        OnConvertTreeDTOInit(contextData);
        List<MyCategory> domains;
        if (parentID is null)
        {
            domains = await DefaultRepository.FindAsync(m => true, m => m.Index, SortOrder.Ascending);
        }
        else
        {
            domains = DefaultRepository.GetAllRecursiveChildren(parentID.Value);
            domains = [.. domains.OrderBy(m => m.Index)];
        }
        OnConvertTreeDTOBefore(domains, contextData);
        List<MyCategoryTreeListDTO> result = domains.ToTree<MyCategory, MyCategoryTreeListDTO>(parentID, (dto, domain) =>
        {
            OnConvertTreeDTO(dto, domain, contextData);
        }, true);
        OnConvertTreeDTOAfter(result, domains, contextData);
        return result;
    }

    /// <summary>
    /// 转换树DTO初始化时
    /// </summary>
    /// <param name="contextData"></param>
    partial void OnConvertTreeDTOInit(Dictionary<string, object> contextData);

    /// <summary>
    /// 转换树DTO之前
    /// </summary>
    /// <param name="domains"></param>
    /// <param name="contextData"></param>
    partial void OnConvertTreeDTOBefore(List<MyCategory> domains, Dictionary<string, object> contextData);

    /// <summary>
    /// 转换树DTO
    /// </summary>
    /// <param name="dto"></param>
    /// <param name="domain"></param>
    /// <param name="contextData"></param>
    partial void OnConvertTreeDTO(MyCategoryTreeListDTO dto, MyCategory domain, Dictionary<string, object> contextData);

    /// <summary>
    /// 转换树DTO之后
    /// </summary>
    /// <param name="dtos"></param>
    /// <param name="domains"></param>
    /// <param name="contextData"></param>
    partial void OnConvertTreeDTOAfter(List<MyCategoryTreeListDTO> dtos, List<MyCategory> domains, Dictionary<string, object> contextData);

    /// <summary>
    /// 移动树节点
    /// </summary>
    /// <param name="model"></param>
    /// <returns></returns>
    public async Task MoveTreeNodeAsync(MoveTreeNodeAndIndexModel model)
    {
        Dictionary<string, object> contextData = [];
        OnMoveTreeAndIndexBefore(model, contextData);
        List<MyCategory> domains = await ServiceImplHelper.MoveAsync<IMyCategoryRepository, MyCategory>(model, DefaultRepository, [nameof(MyCategory.ParentID)]);
        OnMoveTreeAndIndexAfter(model, contextData, domains);
        foreach (MyCategory domain in domains)
        {
            UnitOfWork.RegisterEdit(domain);
        }
        await UnitOfWork.CommitAsync();
    }

    /// <summary>
    /// 移动树节点前
    /// </summary>
    /// <param name="model"></param>
    /// <param name="contextData"></param>
    /// <returns></returns>
    partial void OnMoveTreeAndIndexBefore(MoveTreeNodeAndIndexModel model, Dictionary<string, object> contextData);

    /// <summary>
    /// 移动树节点后
    /// </summary>
    /// <param name="model"></param>
    /// <param name="contextData"></param>
    /// <param name="domain"></param>
    /// <returns></returns>
    partial void OnMoveTreeAndIndexAfter(MoveTreeNodeAndIndexModel model, Dictionary<string, object> contextData, List<MyCategory> domain);
}