/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.IndexGeneratorCodePlug+<GeneratorServiceImplCodeAsync>d__13.MoveNext */
using Materal.MergeBlock.Abstractions.Models;
using MMB.Demo.Abstractions.Domain;

namespace MMB.Demo.Application.Services;

/// <summary>
/// 服务(Index)
/// </summary>
public partial class MyListServiceImpl
{
    /// <summary>
    /// 移动位序
    /// </summary>
    /// <param name="model"></param>
    /// <returns></returns>
    public async Task MoveIndexAsync(MoveIndexModel model)
    {
        Dictionary<string, object> contextData = [];
        OnMoveIndexBefore(model, contextData);
        List<MyList> domains = await ServiceImplHelper.MoveAsync<IMyListRepository, MyList>(model, DefaultRepository, []);
        OnMoveIndexAfter(model, contextData, domains);
        foreach (MyList domain in domains)
        {
            UnitOfWork.RegisterEdit(domain);
        }
        await UnitOfWork.CommitAsync();
    }

    /// <summary>
    /// 移动位序之前
    /// </summary>
    /// <param name="model"></param>
    /// <param name="contextData"></param>
    /// <returns></returns>
    partial void OnMoveIndexBefore(MoveIndexModel model, Dictionary<string, object> contextData);

    /// <summary>
    /// 移动位序之后
    /// </summary>
    /// <param name="model"></param>
    /// <param name="contextData"></param>
    /// <param name="domains"></param>
    /// <returns></returns>
    partial void OnMoveIndexAfter(MoveIndexModel model, Dictionary<string, object> contextData, List<MyList> domains);
}