/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesGeneratorCodePlug.GeneratorServiceImplsCodeAsync */

using MMB.Demo.Abstractions.DTO.MyList;
using MMB.Demo.Abstractions.Services.Models.MyList;

namespace MMB.Demo.Application.Services
{
    /// <summary>
    /// 服务
    /// </summary>
    public partial class MyListServiceImpl : BaseServiceImpl<AddMyListModel, EditMyListModel, QueryMyListModel, MyListDTO, MyListListDTO, IMyListRepository, MyList, IDemoUnitOfWork>, IMyListService, IScopedDependency<IMyListService>
    {
    }
}
