/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesGeneratorCodePlug.GeneratorServiceImplsCodeAsync */

using MMB.Demo.Abstractions.DTO.MyTree;
using MMB.Demo.Abstractions.Services.Models.MyTree;

namespace MMB.Demo.Application.Services
{
    /// <summary>
    /// 服务
    /// </summary>
    public partial class MyTreeServiceImpl : BaseServiceImpl<AddMyTreeModel, EditMyTreeModel, QueryMyTreeModel, MyTreeDTO, MyTreeListDTO, IMyTreeRepository, MyTree, IDemoUnitOfWork>, IMyTreeService, IScopedDependency<IMyTreeService>
    {
    }
}
