/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.TreeGeneratorCodePlug+<GeneratorServiceImplCodeAsync>d__14.MoveNext */
using Materal.MergeBlock.Abstractions.Models;
using MMB.Demo.Abstractions.Domain;
using MMB.Demo.Abstractions.DTO.MyTree;

namespace MMB.Demo.Application.Services;

/// <summary>
/// 服务(Tree)
/// </summary>
public partial class MyTreeServiceImpl
{
    /// <summary>
    /// 获得树列表
    /// </summary>
    /// <param name="parentID"></param>
    /// <returns></returns>
    public async Task<List<MyTreeTreeListDTO>> GetTreeListAsync(Guid? parentID)
    {
        Dictionary<string, object> contextData = [];
        OnConvertTreeDTOInit(contextData);
        List<MyTree> domains;
        if (parentID is null)
        {
            domains = await DefaultRepository.FindAsync(m => true);
        }
        else
        {
            domains = DefaultRepository.GetAllRecursiveChildren(parentID.Value);
        }
        OnConvertTreeDTOBefore(domains, contextData);
        List<MyTreeTreeListDTO> result = domains.ToTree<MyTree, MyTreeTreeListDTO>(parentID, (dto, domain) =>
        {
            OnConvertTreeDTO(dto, domain, contextData);
        }, true);
        OnConvertTreeDTOAfter(result, domains, contextData);
        return result;
    }

    /// <summary>
    /// 转换树DTO初始化时
    /// </summary>
    /// <param name="contextData"></param>
    partial void OnConvertTreeDTOInit(Dictionary<string, object> contextData);

    /// <summary>
    /// 转换树DTO之前
    /// </summary>
    /// <param name="domains"></param>
    /// <param name="contextData"></param>
    partial void OnConvertTreeDTOBefore(List<MyTree> domains, Dictionary<string, object> contextData);

    /// <summary>
    /// 转换树DTO
    /// </summary>
    /// <param name="dto"></param>
    /// <param name="domain"></param>
    /// <param name="contextData"></param>
    partial void OnConvertTreeDTO(MyTreeTreeListDTO dto, MyTree domain, Dictionary<string, object> contextData);

    /// <summary>
    /// 转换树DTO之后
    /// </summary>
    /// <param name="dtos"></param>
    /// <param name="domains"></param>
    /// <param name="contextData"></param>
    partial void OnConvertTreeDTOAfter(List<MyTreeTreeListDTO> dtos, List<MyTree> domains, Dictionary<string, object> contextData);
    
    /// <summary>
    /// 移动树节点
    /// </summary>
    /// <param name="model"></param>
    /// <returns></returns>
    public async Task MoveTreeNodeAsync(MoveTreeNodeModel model)
    {
        Dictionary<string, object> contextData = [];
        OnMoveTreeBefore(model, contextData);
        MyTree domain = await ServiceImplHelper.MoveAsync<IMyTreeRepository, MyTree>(model, DefaultRepository);
        OnMoveTreeAfter(model, contextData, domain);
        UnitOfWork.RegisterEdit(domain);
        await UnitOfWork.CommitAsync();
    }

    /// <summary>
    /// 移动树节点之前
    /// </summary>
    /// <param name="model"></param>
    /// <param name="contextData"></param>
    /// <returns></returns>
    partial void OnMoveTreeBefore(MoveTreeNodeModel model, Dictionary<string, object> contextData);

    /// <summary>
    /// 移动树节点之后
    /// </summary>
    /// <param name="model"></param>
    /// <param name="contextData"></param>
    /// <param name="domain"></param>
    /// <returns></returns>
    partial void OnMoveTreeAfter(MoveTreeNodeModel model, Dictionary<string, object> contextData, MyTree domain);
}