/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.EnumControllerGeneratorCodePlug+<AfterExcuteAsync>d__2.MoveNext */using Microsoft.AspNetCore.Authorization;
using MMB.Demo.Abstractions.Enums;

namespace MMB.Demo.Abstractions.HttpClient
{
    /// <summary>
    /// 枚举控制器
    /// </summary>
    [AllowAnonymous]
    public partial class EnumsController : DemoController
    {
        /// <summary>
        /// 获取所有性别枚举
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ResultModel<List<KeyValueModel<Sex>>> GetAllSex()
        {
            List<KeyValueModel<Sex>> result = KeyValueModel<Sex>.GetAllCode();
            return ResultModel<List<KeyValueModel<Sex>>>.Success(result, "获取成功");
        }
    }
}
