/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.TreeAndIndexGeneratorCodePlug+<GeneratorControllerImplCodeAsync>d__13.MoveNext */
using Materal.MergeBlock.Abstractions.Models;
using MMB.Demo.Abstractions.DTO.MyCategory;

namespace MMB.Demo.Application.Controllers;

/// <summary>
/// 控制器(TreeAndIndex)
/// </summary>
public partial class MyCategoryController
{
    /// <summary>
    /// 获得树列表
    /// </summary>
    /// <param name=""parentID""></param>
    /// <returns></returns>
    [HttpGet]
    public async Task<ResultModel<List<MyCategoryTreeListDTO>>> GetTreeListAsync(Guid? parentID)
    {
        List<MyCategoryTreeListDTO> result = await DefaultService.GetTreeListAsync(parentID);
        return ResultModel<List<MyCategoryTreeListDTO>>.Success(result, "获得树列表成功");
    }

    /// <summary>
    /// 移动树节点
    /// </summary>
    /// <param name="requestModel"></param>
    /// <returns></returns>    
    [HttpPut]
    public async Task<ResultModel> MoveTreeNodeAsync(MoveTreeNodeAndIndexRequestModel requestModel)
    {
        MoveTreeNodeAndIndexModel model = Mapper.Map<MoveTreeNodeAndIndexModel>(requestModel) ?? throw new MMBException("映射失败");
        await DefaultService.MoveTreeNodeAsync(model);
        return ResultModel.Success("移动树节点成功");
    }
}