/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorControllersCodeAsync>d__7.MoveNext */

using MMB.Demo.Abstractions.DTO.MyCategory;
using MMB.Demo.Abstractions.RequestModel.MyCategory;
using MMB.Demo.Abstractions.Services.Models.MyCategory;

namespace MMB.Demo.Application.Controllers;

/// <summary>
/// 控制器
/// </summary>

public partial class MyCategoryController : DemoController<AddMyCategoryRequestModel, EditMyCategoryRequestModel, QueryMyCategoryRequestModel, AddMyCategoryModel, EditMyCategoryModel, QueryMyCategoryModel, MyCategoryDTO, MyCategoryListDTO, IMyCategoryService>, IMyCategoryController
{
}
