/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorControllersCodeAsync>d__7.MoveNext */

using MMB.Demo.Abstractions.DTO.MyList;
using MMB.Demo.Abstractions.RequestModel.MyList;
using MMB.Demo.Abstractions.Services.Models.MyList;

namespace MMB.Demo.Application.Controllers;

/// <summary>
/// 控制器
/// </summary>

public partial class MyListController : DemoController<AddMyListRequestModel, EditMyListRequestModel, QueryMyListRequestModel, AddMyListModel, EditMyListModel, QueryMyListModel, MyListDTO, MyListListDTO, IMyListService>, IMyListController
{
}
