/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.IndexGeneratorCodePlug+<GeneratorControllerImplCodeAsync>d__17.MoveNext */
using Materal.MergeBlock.Abstractions.Models;

namespace MMB.Demo.Application.Controllers;

/// <summary>
/// 控制器(Index)
/// </summary>
public partial class MyListController
{
    /// <summary>
    /// 移动位序
    /// </summary>
    /// <param name="requestModel"></param>
    /// <returns></returns>    
    [HttpPut]
    public async Task<ResultModel> MoveIndexAsync(MoveIndexRequestModel requestModel)
    {
        MoveIndexModel model = Mapper.Map<MoveIndexModel>(requestModel) ?? throw new MMBException("映射失败");
        await DefaultService.MoveIndexAsync(model);
        return ResultModel.Success("移动位序成功");
    }
}