/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorControllersCodeAsync>d__7.MoveNext */

using MMB.Demo.Abstractions.DTO.MyTree;
using MMB.Demo.Abstractions.RequestModel.MyTree;
using MMB.Demo.Abstractions.Services.Models.MyTree;

namespace MMB.Demo.Application.Controllers;

/// <summary>
/// 控制器
/// </summary>

public partial class MyTreeController : DemoController<AddMyTreeRequestModel, EditMyTreeRequestModel, QueryMyTreeRequestModel, AddMyTreeModel, EditMyTreeModel, QueryMyTreeModel, MyTreeDTO, MyTreeListDTO, IMyTreeService>, IMyTreeController
{
}
