/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.TreeGeneratorCodePlug+<GeneratorControllerImplCodeAsync>d__18.MoveNext */
using Materal.MergeBlock.Abstractions.Models;
using MMB.Demo.Abstractions.DTO.MyTree;

namespace MMB.Demo.Application.Controllers;

/// <summary>
/// 控制器(Tree)
/// </summary>
public partial class MyTreeController
{
    /// <summary>
    /// 获得树列表
    /// </summary>
    /// <param name=""parentID""></param>
    /// <returns></returns>
    [HttpGet]
    public async Task<ResultModel<List<MyTreeTreeListDTO>>> GetTreeListAsync(Guid? parentID)
    {
        List<MyTreeTreeListDTO> result = await DefaultService.GetTreeListAsync(parentID);
        return ResultModel<List<MyTreeTreeListDTO>>.Success(result, "获得树列表成功");
    }

    /// <summary>
    /// 移动树节点
    /// </summary>
    /// <param name="requestModel"></param>
    /// <returns></returns>    
    [HttpPut]
    public async Task<ResultModel> MoveTreeNodeAsync(MoveTreeNodeRequestModel requestModel)
    {
        MoveTreeNodeModel model = Mapper.Map<MoveTreeNodeModel>(requestModel) ?? throw new MMBException("映射失败");
        await DefaultService.MoveTreeNodeAsync(model);
        return ResultModel.Success("移动树节点成功");
    }
}