/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RequesetModelGeneratorCodePlug+<GeneratorAddRequestModelAsync>d__8.MoveNext */

namespace MMB.Demo.Abstractions.RequestModel.MyTree;
/// <summary>
/// 添加请求模型
/// </summary>
public partial class AddMyTreeRequestModel : IAddRequestModel
{
    [Required]
    public string Name { get; set; } = string.Empty;
    public Guid? ParentID { get; set; }
}
