/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.TreeGeneratorCodePlug+<GeneratorTreeDTOCodeAsync>d__10.MoveNext */
namespace MMB.Demo.Abstractions.DTO.MyCategory;

/// <summary>
/// 树列表数据传输模型
/// </summary>
public partial class MyCategoryTreeListDTO : MyCategoryListDTO, ITreeDTO<MyCategoryTreeListDTO>
{
    /// <summary>
    /// 子级
    /// </summary>
    public List<MyCategoryTreeListDTO> Children { get; set; } = [];
}