/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.DTOGeneratorCodePlug+<GeneratorDTOModelAsync>d__8.MoveNext */

namespace MMB.Demo.Abstractions.DTO.MyCategory;

/// <summary>
/// 数据传输模型
/// </summary>
public partial class MyCategoryDTO : MyCategoryListDTO, IDTO
{
}
