/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.DTOGeneratorCodePlug+<GeneratorListDTOModelAsync>d__7.MoveNext */

namespace MMB.Demo.Abstractions.DTO.MyCategory;

/// <summary>
/// 列表数据传输模型
/// </summary>
public partial class MyCategoryListDTO : IListDTO
{
    /// <summary>
    /// 唯一标识
    /// </summary>
    [Required(ErrorMessage = "唯一标识为空")]
    public Guid ID { get; set; }
    /// <summary>
    /// 创建时间
    /// </summary>
    [Required(ErrorMessage = "创建时间为空")]
    public DateTime CreateTime { get; set; }
    [Required]
    public string Name { get; set; } = string.Empty;
    public Guid? ParentID { get; set; }
    [Required]
    public int Index { get; set; }
}
