/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ServicesModelGeneratorCodePlug+<GeneratorAddModelAsync>d__8.MoveNext */

namespace MMB.Demo.Abstractions.Services.Models.MyList;
/// <summary>
/// 添加模型
/// </summary>
public partial class AddMyListModel : IAddServiceModel
{
    [Required]
    public string Name { get; set; } = string.Empty;
}
