<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../../../Common.props" />
	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\Materal.MergeBlock.GeneratorCode\Materal.MergeBlock.GeneratorCode.csproj" />
		<ProjectReference Include="..\..\..\Materal.MergeBlock.Web.Abstractions\Materal.MergeBlock.Web.Abstractions.csproj" />
		<ProjectReference Include="..\..\MMB.Core\MMB.Core.Repository\MMB.Core.Repository.csproj" />
	</ItemGroup>
</Project>
