/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.TreeAndIndexGeneratorCodePlug+<GeneratorIControllerCodeAsync>d__11.MoveNext */
using Materal.MergeBlock.Abstractions.Models;
using MMB.Demo.Abstractions.DTO.MyCategory;

namespace MMB.Demo.Abstractions.Controllers;

/// <summary>
/// 控制器(TreeAndIndex)
/// </summary>
public partial interface IMyCategoryController
{
    /// <summary>
    /// 获得树列表
    /// </summary>
    /// <param name="parentID"></param>
    /// <returns></returns>
    [HttpGet]
    Task<ResultModel<List<MyCategoryTreeListDTO>>> GetTreeListAsync(Guid? parentID);

    /// <summary>
    /// 移动树节点
    /// </summary>
    /// <param name="requestModel"></param>
    /// <returns></returns>
    [HttpPut]
    Task<ResultModel> MoveTreeNodeAsync(MoveTreeNodeAndIndexRequestModel requestModel);
}