/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorIControllerCodeAsync>d__6.MoveNext */

using MMB.Demo.Abstractions.DTO.MyCategory;
using MMB.Demo.Abstractions.RequestModel.MyCategory;

namespace MMB.Demo.Abstractions.Controllers;

/// <summary>
/// 控制器
/// </summary>
public partial interface IMyCategoryController : IMergeBlockController<AddMyCategoryRequestModel, EditMyCategoryRequestModel, QueryMyCategoryRequestModel, MyCategoryDTO, MyCategoryListDTO>
{
}
