/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorIControllerCodeAsync>d__6.MoveNext */

using MMB.Demo.Abstractions.DTO.MyList;
using MMB.Demo.Abstractions.RequestModel.MyList;

namespace MMB.Demo.Abstractions.Controllers;

/// <summary>
/// 控制器
/// </summary>
public partial interface IMyListController : IMergeBlockController<AddMyListRequestModel, EditMyListRequestModel, QueryMyListRequestModel, MyListDTO, MyListListDTO>
{
}
