/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.IndexGeneratorCodePlug+<GeneratorIControllerCodeAsync>d__15.MoveNext */
using Materal.MergeBlock.Abstractions.Models;

namespace MMB.Demo.Abstractions.Controllers;

/// <summary>
/// 控制器(Index)
/// </summary>
public partial interface IMyListController
{
    /// <summary>
    /// 移动位序
    /// </summary>
    /// <param name="requestModel"></param>
    /// <returns></returns>
    [HttpPut]
    Task<ResultModel> MoveIndexAsync(MoveIndexRequestModel requestModel);
}