/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerGeneratorCodePlug+<GeneratorIControllerCodeAsync>d__6.MoveNext */

using MMB.Demo.Abstractions.DTO.MyTree;
using MMB.Demo.Abstractions.RequestModel.MyTree;

namespace MMB.Demo.Abstractions.Controllers;

/// <summary>
/// 控制器
/// </summary>
public partial interface IMyTreeController : IMergeBlockController<AddMyTreeRequestModel, EditMyTreeRequestModel, QueryMyTreeRequestModel, MyTreeDTO, MyTreeListDTO>
{
}
