/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.TreeGeneratorCodePlug+<GeneratorIControllerCodeAsync>d__16.MoveNext */
using Materal.MergeBlock.Abstractions.Models;
using MMB.Demo.Abstractions.DTO.MyTree;

namespace MMB.Demo.Abstractions.Controllers;

/// <summary>
/// 控制器(Tree)
/// </summary>
public partial interface IMyTreeController
{
    /// <summary>
    /// 获得树列表
    /// </summary>
    /// <param name="parentID"></param>
    /// <returns></returns>
    [HttpGet]
    Task<ResultModel<List<MyTreeTreeListDTO>>> GetTreeListAsync(Guid? parentID);

    /// <summary>
    /// 移动树节点
    /// </summary>
    /// <param name="requestModel"></param>
    /// <returns></returns>
    [HttpPut]
    Task<ResultModel> MoveTreeNodeAsync(MoveTreeNodeRequestModel requestModel);
}