/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerAccessorsGeneratorCodePlug+<GeneratorControllerAccessorAsync>d__9.MoveNext */

using Materal.MergeBlock.Abstractions.Models;
using MMB.Demo.Abstractions.DTO.MyCategory;
using MMB.Demo.Abstractions.RequestModel.MyCategory;

namespace MMB.Demo.Abstractions.ControllerAccessors;

/// <summary>
/// 控制器(TreeAndIndex)访问器
/// </summary>

public partial class MyCategoryControllerAccessor(IServiceProvider serviceProvider) : BaseControllerAccessor<IMyCategoryController, AddMyCategoryRequestModel, EditMyCategoryRequestModel, QueryMyCategoryRequestModel, MyCategoryDTO, MyCategoryListDTO>(serviceProvider), IMyCategoryController

{
    /// <summary>
    /// 项目名称
    /// </summary>
    public override string ProjectName => "MMB";
    /// <summary>
    /// 模块名称
    /// </summary>
    public override string ModuleName => "Demo";
    /// <summary>
    /// 获得树列表
    /// </summary>
    /// <param name="parentID"></param>
    /// <returns></returns>
    public async Task<ResultModel<List<MyCategoryTreeListDTO>>> GetTreeListAsync(Guid? parentID)
        => await HttpHelper.SendAsync<IMyCategoryController, ResultModel<List<MyCategoryTreeListDTO>>>(ProjectName, ModuleName, nameof(GetTreeListAsync), []);
    /// <summary>
    /// 移动树节点
    /// </summary>
    /// <param name="requestModel"></param>
    /// <returns></returns>
    public async Task<ResultModel> MoveTreeNodeAsync(MoveTreeNodeAndIndexRequestModel requestModel)
        => await HttpHelper.SendAsync<IMyCategoryController, ResultModel>(ProjectName, ModuleName, nameof(MoveTreeNodeAsync), []);
}