/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerAccessorsGeneratorCodePlug+<GeneratorControllerAccessorAsync>d__9.MoveNext */

using Materal.MergeBlock.Abstractions.Models;
using MMB.Demo.Abstractions.DTO.MyList;
using MMB.Demo.Abstractions.RequestModel.MyList;

namespace MMB.Demo.Abstractions.ControllerAccessors;

/// <summary>
/// 控制器(Index)访问器
/// </summary>

public partial class MyListControllerAccessor(IServiceProvider serviceProvider) : BaseControllerAccessor<IMyListController, AddMyListRequestModel, EditMyListRequestModel, QueryMyListRequestModel, MyListDTO, MyListListDTO>(serviceProvider), IMyListController

{
    /// <summary>
    /// 项目名称
    /// </summary>
    public override string ProjectName => "MMB";
    /// <summary>
    /// 模块名称
    /// </summary>
    public override string ModuleName => "Demo";
    /// <summary>
    /// 移动位序
    /// </summary>
    /// <param name="requestModel"></param>
    /// <returns></returns>
    public async Task<ResultModel> MoveIndexAsync(MoveIndexRequestModel requestModel)
        => await HttpHelper.SendAsync<IMyListController, ResultModel>(ProjectName, ModuleName, nameof(MoveIndexAsync), []);
}