/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerAccessorsGeneratorCodePlug+<GeneratorControllerAccessorAsync>d__9.MoveNext */

using Materal.MergeBlock.Abstractions.Models;
using MMB.Demo.Abstractions.DTO.MyTree;
using MMB.Demo.Abstractions.RequestModel.MyTree;

namespace MMB.Demo.Abstractions.ControllerAccessors;

/// <summary>
/// 控制器(Tree)访问器
/// </summary>

public partial class MyTreeControllerAccessor(IServiceProvider serviceProvider) : BaseControllerAccessor<IMyTreeController, AddMyTreeRequestModel, EditMyTreeRequestModel, QueryMyTreeRequestModel, MyTreeDTO, MyTreeListDTO>(serviceProvider), IMyTreeController

{
    /// <summary>
    /// 项目名称
    /// </summary>
    public override string ProjectName => "MMB";
    /// <summary>
    /// 模块名称
    /// </summary>
    public override string ModuleName => "Demo";
    /// <summary>
    /// 获得树列表
    /// </summary>
    /// <param name="parentID"></param>
    /// <returns></returns>
    public async Task<ResultModel<List<MyTreeTreeListDTO>>> GetTreeListAsync(Guid? parentID)
        => await HttpHelper.SendAsync<IMyTreeController, ResultModel<List<MyTreeTreeListDTO>>>(ProjectName, ModuleName, nameof(GetTreeListAsync), []);
    /// <summary>
    /// 移动树节点
    /// </summary>
    /// <param name="requestModel"></param>
    /// <returns></returns>
    public async Task<ResultModel> MoveTreeNodeAsync(MoveTreeNodeRequestModel requestModel)
        => await HttpHelper.SendAsync<IMyTreeController, ResultModel>(ProjectName, ModuleName, nameof(MoveTreeNodeAsync), []);
}