/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.ControllerAccessorsGeneratorCodePlug+<GeneratorControllerAccessorAsync>d__3.MoveNext */using MMB.Demo.Abstractions.DTO.User;
using MMB.Demo.Abstractions.RequestModel.User;

namespace MMB.Demo.Abstractions.ControllerAccessors
{
    /// <summary>
    /// 用户控制器访问器
    /// </summary>
    public partial class UserControllerAccessor(IServiceProvider serviceProvider) : BaseControllerAccessor<IUserController, AddUserRequestModel, EditUserRequestModel, QueryUserRequestModel, UserDTO, UserListDTO>(serviceProvider), IUserController
    {
        /// <summary>
        /// 项目名称
        /// </summary>
        public override string ProjectName => "MMB";
        /// <summary>
        /// 模块名称
        /// </summary>
        public override string ModuleName => "Demo";
    }
}
