/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorEntityConfigCodeAsync>d__9.MoveNext */

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MMB.Demo.Repository.EntityConfigs;
/// <summary>
/// 配置基类
/// </summary>
public class MyListConfigBase : BaseEntityConfig<MyList>
{
    /// <summary>
    /// 配置
    /// </summary>
    public override void Configure(EntityTypeBuilder<MyList> builder)
    {
        builder = BaseConfigure(builder);
        builder.ToTable(m => m.HasComment(""));
        builder.Property(e => e.Name)
            .IsRequired()
            .HasComment("");
        builder.Property(e => e.Index)
            .IsRequired()
            .HasComment("");
    }
}
/// <summary>
/// 配置类
/// </summary>
public partial class MyListConfig : MyListConfigBase { }
