/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.TreeGeneratorCodePlug+<GeneratorTreeDTOCodeAsync>d__10.MoveNext */
namespace MMB.Demo.Abstractions.DTO.MyTree;

/// <summary>
/// 树列表数据传输模型
/// </summary>
public partial class MyTreeTreeListDTO : MyTreeListDTO, ITreeDTO<MyTreeTreeListDTO>
{
    /// <summary>
    /// 子级
    /// </summary>
    public List<MyTreeTreeListDTO> Children { get; set; } = [];
}