/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RequesetModelGeneratorCodePlug+<GeneratorAddRequestModelAsync>d__8.MoveNext */

namespace MMB.Demo.Abstractions.RequestModel.MyList;
/// <summary>
/// 添加请求模型
/// </summary>
public partial class AddMyListRequestModel : IAddRequestModel
{
    [Required]
    public string Name { get; set; } = string.Empty;
}
