/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.TreeGeneratorCodePlug+<GeneratorIRepositoryCodeAsync>d__6.MoveNext */
using Materal.MergeBlock.Repository.Abstractions.Repositories;

namespace MMB.Demo.Abstractions.Repositories;

/// <summary>
/// 仓储(Tree)
/// </summary>
public partial interface IMyCategoryRepository : ITreeRepository<MyCategory>
{
}