/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.RepositoryGeneratorCodePlug+<GeneratorIRepositoryCodeAsync>d__11.MoveNext */

namespace MMB.Demo.Abstractions.Repositories;
/// <summary>
/// 仓储
/// </summary>

public partial interface IMyCategoryRepository : IDemoRepository<MyCategory>

{
}
