/* Generated by: Materal.MergeBlock.GeneratorCode.DefaultPlug.IndexGeneratorCodePlug+<GeneratorIRepositoryCodeAsync>d__7.MoveNext */
namespace MMB.Demo.Abstractions.Repositories;
/// <summary>
/// 仓储(Index)
/// </summary>
public partial interface IMyListRepository
{
    /// <summary>
    /// 获取最大位序
    /// </summary>
    /// <returns></returns>
    Task<int> GetMaxIndexAsync();
}